name: Upload README to Google Drive
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'README.md'
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          filename: README.md
          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
          overwrite: true
